### ISSUE TITLE
Overfitting and increasing class loss

### ISSUE THREAD

**Issue by ArpanGyawali** [MIC-DKFZ/nnDetection#290]
I am working on LVO detection using 3d MIP images. Half of the image have no annotations as they are negative case, but are important for training to learn negative features. And the other half have 1 and sometimes 2 LVO segmentation associated with each image for positive case. The segmentations from 2 to 3 slices.
As i am training the training loss goes negative after 18-19 epochs(Total 25 epochs) and the validation loss starts increasing after very few epochs. I think this is due to overfitting.
I have around 220 training data with (80:20) train val split. That means each fold contains only 44 data. Is this because of less training data. 
Also, when looking at the validation class loss, its increasing rapidly after very few epochs, while the regression loss starts at negative value and gradually decrease. Why is this?
![image](https://github.com/user-attachments/assets/154bd102-9fe4-4388-aad8-e84a6b09b49b)
![image](https://github.com/user-attachments/assets/32987bcf-a91f-45be-aed5-122eddbde704)

When i use some more augmentation, then the validation loss increase by a bit (i.e. from 0.7 to 0.5), but still its not good and overfitting.
![image](https://github.com/user-attachments/assets/3743cd7f-bca0-4e73-b565-6c60e4c65d7f)

Doesnt nndet use focal loss as class loss?  
Can you give some insights to how i can increase acccuracy of my model. If more information is required i can provide.

**Comment by andres2631996** [comment]
By default, nnDetection utilizes BCE as class loss. You could try to use focal loss adding the following snippet to /nndet/ptmodule/retinaunet/v001.py

```
from nndet.arch.heads.classifier import FocalClassifier

@MODULE_REGISTRY.register
class RetinaUNetV001Focal(RetinaUNetModule):
    base_conv_cls = ConvInstanceRelu
    head_conv_cls = ConvGroupRelu

    head_cls = DetectionHeadHNMNative
    head_classifier_cls = FocalClassifier
    head_regressor_cls = GIoURegressor
    matcher_cls = ATSSMatcher
    segmenter_cls = DiCESegmenterFgBg
```

And then run:

`nndet_train TASK -o exp.fold=0 module=RetinaUNetV001Focal`


It may also be that your objects are very small. If the objects you want to detect are just like 3x3x3 in images with hundreds of voxels in each dimension, as you claim, it may be that the imbalance is just very strong. Can you check the size of any of your boxes in _det_data/TASK/preprocessed/PLAN/imagesTr/CASEID_boxes.pkl_?

If you are working with LVOs, you could define larger ROIs in the segmentations in _raw_splitted/labelsTs_ to alleviate the imbalance. LVOs are just regions of interest, unlike tumors or other lesion types with a defined boundary, and that allows for flexibility in its object definition

**Comment by ArpanGyawali** [comment]
Thank you so much. @andres2631996 
I tried the focal loss as you said but the ap@0.1 as well as dice score doesn't move more than 0.55 with average of 0.5.
The loss goes negative just after 3-4 epoch and overfitting  has reduced by a little but. But the results are still not good enough.
 
The config is something like this,
```
# @package **global**
defaults:
  - augmentation: base_more
module: RetinaUNetV001
predictor: BoxPredictorSelective
plan: D3V001_3d # plan used for training
planner: D3V001 # planner used for preprocessing
  
augment_cfg:
  augmentation: ${augmentation}
  num_train_batches_per_epoch: ${trainer_cfg.num_train_batches_per_epoch}
  num_val_batches_per_epoch: ${trainer_cfg.num_val_batches_per_epoch}
  dataloader: "DataLoader{}DOffset"
  # oversample_foreground_percent: 0.5 # ratio of fg and bg in batches
  oversample_foreground_percent: 0.75 # increased
  dataloader_kwargs: {}
  num_threads: ${oc.env:det_num_threads, "12"}
  num_cached_per_thread: 2
  multiprocessing: True # only deactivate this if debugging
  # Additional overwrites
  # patch_size; Default: plan
  # batch_size; Default: plan
  # splits; Default: splits_final
trainer_cfg:
  gpus: 2 # number of gpus
  accelerator: # distributed backend
  precision: 16 # mixed precision
  amp_backend: native # mixed precision backend
  amp_level: O1 # when mixed precision backend is APEX use O1
  # Per default training is deterministic, non-deterministic allows
  # cudnn.benchmark which can give up to 20% performance. Set this to false
  # to perform non-deterministic training
  deterministic: False
  benchmark: False  
  monitor_key: "mAP_IoU_0.10_0.50_0.05_MaxDet_100" # used to determine the best model
  monitor_mode: "max" # metric operation mode "min" or "max"
  max_num_epochs: 15 # max number of epochs
  num_train_batches_per_epoch: 400 # number of train batches per epoch
  num_val_batches_per_epoch: 100 # number of val batches per epoch
  initial_lr: 0.01 # initial learning rate to start with (Preiously->0.1)
  sgd_momentum: 0.9 # momentum term
  sgd_nesterov: True # nesterov momentum
  weight_decay: 5.e-4 # weight decay for optimizer(Previous -> 3.e-5)
  warm_iterations: 1500 # number of iterations with warmup
  warm_lr: 1.e-6 # learning rate to start warmup from
  poly_gamma: 0.9
  swa_epochs: 5 # number of epochs to run swa with cyclic learning rate
  # sweep_ckpt: Select checkpoint identifier for sweeping. Default "last".
model_cfg:
  encoder_kwargs: {} # keyword arguments passed to encoder
  decoder_kwargs: # keyword arguments passed to decoder
    min_out_channels: 16         #from 8
    upsampling_mode: "transpose"
    num_lateral: 2               #from 1
    norm_lateral: True           #from false
    activation_lateral: True     #from false
    num_out: 1
    norm_out: True
    activation_out: True
  head_kwargs: {} # keyword arguments to passed to head
  head_classifier_kwargs: # keyword arguments passed to classifier in head
    num_convs: 2
    norm_channels_per_group: 16
    norm_affine: True
    reduction: "mean"
    # loss_weight: 1.
    # prior_prob: 0.01
    loss_weight: 2.
    prior_prob: 0.1
  head_regressor_kwargs: # keyword arguments passed to regressor in head
    num_convs: 2
    norm_channels_per_group: 16
    norm_affine: True
    reduction: "sum"
    loss_weight: 1.5
    learn_scale: True
  head_sampler_kwargs: # keyword arguments passed to sampler
    batch_size_per_image: 8 # number of anchors sampled per image (prev-> 32)
    positive_fraction: 0.6 # defines ratio between positive and negative anchors (Prev -> 0.33)
    # hard negatives are sampled from a pool of size:
    # batch_size_per_image * (1 - positive_fraction) * pool_size
    # pool_size: 20
    pool_size: 8
    min_neg: 1 # minimum number of negative anchors sampled per image
  segmenter_kwargs:
    dice_kwargs:
      batch_dice: True
  matcher_kwargs: # keyword arguments passed to matcher
    num_candidates: 4
    center_in_gt: False
  plan_arch_overwrites: {} # overwrite arguments of architecture
  plan_anchors_overwrites: {} # overwrite arguments of anchors
```
