### ISSUE TITLE
[Bug]No dataset.json after runing prepare_mic.py for Task012_LIDC

### ISSUE THREAD

**Issue by hushunda** [MIC-DKFZ/nnDetection#42]
Task: Task012_LIDC
When run nndet_prep, a bug has occurred—— `Did not find dataset.json or dataset.yaml` .
I think the dataset.yml should be generated when running prepare_mic.py.  However, i do not find the generated code in the prepare_mic.py.

**Comment by hushunda** [comment]
In addition, there are a lot of bugs when processing data of Task012_LIDC

**Comment by mibaumgartner** [comment]
Dear @hushunda ,

indeed, I forgot to add the `dataset.yaml` generation to the script (I generated it manually). I'll update the code to include the data, in the meantime you could generate it yourself, here is the info:

```yaml
task: Task012_LIDC

name: LIDC
target_class:
test_labels: False # manually splitted test set

remove_classes: []
reorder_classes: {}
subtract_one_from_classes: False  # subtract one from all classes in mapping

labels:
    "0": "benign"
    "1": "malignant"

modalities:
    "0": "CT"

dim: 3
```

Most of the code is adapted from the original script of the medicaldetectiontoolkit (from [here](https://github.com/MIC-DKFZ/medicaldetectiontoolkit/blob/master/experiments/lidc_exp/preprocessing.py)) and it worked on the data I received from my colleague. Can you specify in more detail which other bugs you mean?

I can see that the current preparation of the data is also somewhat cumbersome and I hope to provide an updated version with the help of newer tools like `pylidc` sometime in the future (PRs from the community are highly appreciated as well).
